version: '3.8'
services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - discovery-server
      - keycloak_web
      - user-management-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - toyota

  discovery-server:
    build:
      context: ./discovery-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - toyota

  report-service:
    build:
      context: ./report-service
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - toyota

  sale-service:
    build:
      context: ./sale-service
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/storage
    networks:
      - toyota

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/storage
    networks:
      - toyota

  user-management-service:
    build:
      context: ./user-management-service
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - discovery-server
      - keycloak_web
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - toyota
    restart: always

  keycloak_web:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: 9414
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 9090
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    depends_on:
      - postgres
    ports:
      - "9090:8080"
    networks:
      - toyota

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=9414
      - POSTGRES_DB=storage
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - toyota

volumes:
  postgres_data:

networks:
  toyota:
    driver: bridge
